#skip 11.18

diff --git a/.github/workflows/pipeline.yml b/.github/workflows/pipeline.yml
--- a/.github/workflows/pipeline.yml
+++ b/.github/workflows/pipeline.yml
@@ -1,7 +1,7 @@
 name: Deployment pipeline
 
 env:
-  SHOULD_DEPLOY: ${{github.event_name == 'push' && github.ref_name == 'main' && !contains(github.event.head_commit.message,'#skip') }}
+  SHOULD_DEPLOY: ${{ github.event_name == 'push' && github.ref_name == 'main' && !contains(github.event.head_commit.message, '#skip') }}
 
 on:
   push:
@@ -18,23 +18,24 @@ jobs:
       - uses: actions/setup-node@v4
         with:
           node-version: '20'
-      - name: Install dependencies
-        run: npm install
 
-      - name: check Style
-        run: npm run eslint
+      - name: Install dependencies
+        run: npm install || (echo "Install dependencies" > fail.txt && exit 1)
+
+      - name: Check Style
+        run: npm run eslint || (echo "Check Style" > fail.txt && exit 1)
 
       - name: Build Frontend
-        run: npm run build
+        run: npm run build || (echo "Build Frontend" > fail.txt && exit 1)
 
-      - name: test
-        run: npm run test
+      - name: Test
+        run: npm run test || (echo "Test" > fail.txt && exit 1)
 
       - name: Install Playwright
         run: npx playwright install --with-deps
 
       - name: Run Playwright Tests
-        run: npm run test:e2e
+        run: npm run test:e2e || (echo "Run Playwright Tests" > fail.txt && exit 1)
 
       - name: Setup Fly
         if: ${{ env.SHOULD_DEPLOY == 'true' }}
@@ -42,9 +43,47 @@ jobs:
 
       - name: Deploy to Fly
         if: ${{ env.SHOULD_DEPLOY == 'true' }}
-        run: flyctl deploy --remote-only
+        run: flyctl deploy --remote-only || (echo "Deploy to Fly" > fail.txt && exit 1)
         env:
           FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
+
+      - name: Parse failed step
+        if: failure()
+        run: echo "FAILED_STEP=$(cat fail.txt)" >> $GITHUB_ENV
+
+      - name: Notify Successful Build
+        uses: stegzilla/discord-notify@v2
+        if: ${{ success() && env.SHOULD_DEPLOY == 'true' }}
+        with:
+          username: The GitHub Times
+          title: A new build was **Majestically** deployed!
+          avatar_url: https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png
+          include_image: false
+          message: |
+            - **URL**: [PokéDex App](https://full-stack-open-pokedex-crimson-violet-4961.fly.dev)
+            - **Author**: ${{ github.event.head_commit.author.username }}
+            - **Commit**: [${{ github.event.head_commit.id }}](${{ github.event.head_commit.url }})
+
+            **Severity**: Info
+          webhook_url: ${{ secrets.DISCORD_WEBHOOK }}
+          colour: '#00FF00'
+
+      - name: Notify Failed Build
+        uses: stegzilla/discord-notify@v2
+        if: failure()
+        with:
+          username: The GitHub Times
+          avatar_url: https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png
+          title: Build **Miserably** Failed!
+          include_image: false
+          message: |
+            - **Failed Step**: ${{ env.FAILED_STEP }}
+            - **Who to blame**: ${{ github.event.head_commit.author.username }}
+            - **Commit**: [${{ github.event.head_commit.id }}](${{ github.event.head_commit.url }})
+
+            **Severity**: Error
+          webhook_url: ${{ secrets.DISCORD_WEBHOOK }}
+          colour: '#FF0000'
 
   tag_release:
     needs: [simple_deployment_pipeline]
@@ -57,40 +96,5 @@ jobs:
         if: ${{ env.SHOULD_DEPLOY == 'true' }}
         uses: anothrNick/github-tag-action@f278d49d30cdd8775cc3e7dd00b5ee11686ee297
         env:
-          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
           DEFAULT_BUMP: patch
-  notify_discord:
-    needs: [simple_deployment_pipeline, tag_release]
-    runs-on: ubuntu-22.04
-    steps:
-      - name: Build Succeeded
-        uses: stegzilla/discord-notify@v2
-        if: ${{ success() && env.SHOULD_DEPLOY == 'true' }}
-        with:
-          username: The GitHub Times
-          title: A new build was **Majesticly** deployed!
-          avatar_url: https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png
-          include_image: false
-          message: |
-            - **URL**: [PokéDex App](https://full-stack-open-pokedex-crimson-violet-4961.fly.dev)
-            - **Author**: ${{github.event.head_commit.author.username}}
-            - **Commit**: [${{github.event.head_commit.id}}](${{github.event.head_commit.URL}})
-
-            **Severity**: Info
-          webhook_url: ${{secrets.DISCORD_WEBHOOK}}
-          colour: #00FF00
-      - name: Build Failed Miserably!
-        uses: stegzilla/discord-notify@v2
-        if: ${{ failure() && env.SHOULD_DEPLOY == 'true' }}
-        with:
-          username: The GitHub Times
-          avatar_url: https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png
-          title: Build **Miserably** Failed!
-          include_image: false
-          message: |
-            - **Who to blame**: ${{github.event.head_commit.author.username}}
-            - **Commit**: [${{github.event.head_commit.id}}](${{github.event.head_commit.URL}})
-
-             **Severity**: Error
-          webhook_url: ${{secrets.DISCORD_WEBHOOK}}
-          colour: #FF0000
